providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["cd server && npm install"]

[phases.start]
cmd = "cd server && npm start"

[start]
cmd = "cd server && npm start"
